routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TrucController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomeController::class)->name('home');


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware('auth', 'admin')->prefix('admin')->group(function () {
    Route::get('dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    Route::get('create-event', [EventController::class, 'create'])->name('admin.event.create');
    Route::post('store-event', [EventController::class, 'store'])->name('admin.event.store');
    Route::get('list-event', [EventController::class, 'list'])->name('admin.event.list');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@section('title')
    {{ 'Tableau de bord' }}
@endsection

@push('styles')
    <link rel="stylesheet" href="/assets/css/dashboard.css">
@endpush

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            Tableau de bord
        </h2>
    </x-slot>

    <div id="dashboard-container">

        <div id="event-section" class="dashboard-section">

            <a href="{{route('admin.event.list')}}" class="list-link">
                
                <i class="fa-solid fa-indent icon"></i>
                <p>événéments</p>

            </a>

            <a href="{{route('admin.event.create')}}" class="create-link">
                <span>+</span>
            </a>

        </div>

        <div id="user-section" class="dashboard-section">

            <a href="#" class="list-link">
                
                <i class="fa-solid fa-users icon"></i>
                <p>Utilisateurs</p>

            </a>

            <a href="#" class="create-link">
                <span>+</span>
            </a>

        </div>

    </div>

</x-app-layout>

resources/views/home.blade.php
<x-guest-layout>

    {{-- Ajout du titre de la page + des styles et des scripts --}}

    @section('title')
        {{ 'Accueil' }}
    @endsection

    @push('scripts')
        <script src="/assets/js/home.js"></script>
    @endpush

    @push('styles')
        <link rel="stylesheet" href="/assets/css/home.css">
    @endpush

    <div id="home-container">

        <div class="top-container">

            <div class="main-image-container">
                <img src="assets/images/home-main-image.webp" alt="Groupe de personnes se réunissant dans la joie">
            </div>

            <div class="slogan-container">
                <h1>Bienvenue sur notre site d'événements communautaires</h1>
                <p class="lead">Organisez et découvrez des événements passionnants près de chez vous.</p>
            </div>

        </div>

        <div id="list-event-container">
    
            <h2 class="title">Evénéments à venir</h2>
    
            @if (count($events)>0)
                
                <div id="event-list">
    
                    @foreach ($events as $event)
                        <a class="event" href="event/{{$event->id}}">

                            <div class="image-container">
                                @if ($event->image)
                                    
                                    <img src="{{ asset('storage/'.$event->image) }}" alt="">

                                @endif
                            </div>

                            <div class="info-container">

                                <h3 class="event-title">{{ $event->title }}</h3>
                                <p class="event-description">@cutText($event->description)</p>

                                <div class="event-date">
                                    <p class="start-date">{{ date('d/m/Y', strtotime($event->start_time)) }}</p>
                                    <span class="date-separator">-</span>
                                    <p class="end-date">{{ date('d/m/Y', strtotime($event->end_time)) }}</p>
                                </div>

                                <div class="attendees-container">
                                    <i class="fa-regular fa-user icon"></i>
                                    <div class="attendees">
                                        0 / {{$event->max_attendees}}
                                    </div>
                                </div>

                                <button class="participate-button">
                                    Participer
                                </button>
                            </div>

                        </a>
                    @endforeach
    
                </div>
    
            @else
    
                <p class="no-event">Aucun événement n'est à venir</p>
    
            @endif
    
        </div>

    </div>



</x-guest-layout>